id=notifications
name=Notifications
description=Discord and Slack webhook notifications for Nimbus events
default=false
min_nimbus_version=0.8.2
main_class=dev.nimbuspowered.nimbus.module.notifications.NotificationsModule
