package dev.nimbus.plugin;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Configuration for the Nimbus Bridge (API connection).
 * Auto-generated by Nimbus Core during deployment.
 */
public class BridgeConfig {

    @SerializedName("api_url")
    private String apiUrl = "http://127.0.0.1:8080";

    @SerializedName("token")
    private String token = "";

    public String getApiUrl() {
        return apiUrl;
    }

    public String getToken() {
        return token;
    }

    public static BridgeConfig load(Path dataDirectory) throws IOException {
        Path configFile = dataDirectory.resolve("bridge.json");
        if (!Files.exists(configFile)) {
            return null;
        }
        String json = Files.readString(configFile);
        return new Gson().fromJson(json, BridgeConfig.class);
    }
}
